###
POST https://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "email":"joshikartikey32@gamil.com",
    "firstName":"kartikey",
    "lastName":"Joshi",
    "password":"pass1234"
}